Add pr_checks.sh and Jenkins file + support scripts
RedHatInsights/backend-starter-app-python pull request #8
Opened 2023-06-28 12:27 UTC by mjholder

Added template scripts from https://github.com/RedHatInsights/cicd-tools/tree/main/examples
Ticket: https://issues.redhat.com/browse/RHCLOUD-26417

2023-07-18 12:10 UTC, Victoremepunto requested changes
It is a good start, but I think we can simplify it further since the Jenkinsfile should be enough to not need pr_check.sh nor build_deploy.sh anymore.

NOTE: `build_deploy` could instead invoke the `make` recipes for building and pushing the images instead.

2023-07-18 12:10 UTC, Victoremepunto commented on Jenkinsfile
> +                    sh './build_deploy.sh'
let's get rid of build_deploy and pr_check if we're going with the Jenkinsfile approach, and call the appropriate Makefile recipes instead (like `make build-image` instead of invoking `build_deploy.sh` script)

2023-07-18 12:10 UTC, Victoremepunto commented on Jenkinsfile
> +                            sh 'bash -x ./unit_test.sh'
same here, replace with `make test` or similar, activating a virtual environment first.

2023-07-18 12:10 UTC, Victoremepunto commented on Jenkinsfile
> +                                source "${CICD_ROOT}/cji_smoke_test.sh"
let's add a dummy recipe for smoke tests and call it here (like `make smoke-tests` or something.

2023-07-18 12:10 UTC, Victoremepunto commented on Jenkinsfile
> +    }
I'd remove this section entirely, put it back in when we have something working, as this requires an actual test result produced to work.

2023-07-18 12:10 UTC, Victoremepunto commented on pr_check.sh
the `Jenkinsfile` is meant to replace ` pr_check.sh` entirely, so I think we can remove this script entirely

2023-07-18 12:10 UTC, Victoremepunto commented on unit_test.sh
I see you added the virtual environment bits here ... still , if we can sort it with a couple of lines in the stage, I don't think we need this script neither (see my previous comment about the test stage).

2023-07-18 13:00 UTC, mjholder commented on Jenkinsfile
> +                    sh './build_deploy.sh'
I updated this to use the makefile recipe

2023-07-18 13:01 UTC, mjholder commented on Jenkinsfile
> +                            sh 'bash -x ./unit_test.sh'
this is also using the makefile recipes to setup a virtual env and run the tests

2023-07-18 13:02 UTC, mjholder commented on pr_check.sh
Ok, I think I got my wires crossed because of when I updated the frontend operator to use a Jenkinsfile, it already had a pr_check script so I thought both were needed. I have removed `pr_check.sh` and `unit_test.sh`

2023-07-18 15:52 UTC, Victoremepunto requested changes
One last comment. Thanks!

2023-07-18 15:52 UTC, Victoremepunto commented on build_deploy.sh
One last thing - since we still have a separate Jenkins job for build_deploy, let's make the `build_deploy.sh` to simply run the make recipes to build and push the image.

2023-07-18 17:51 UTC, mjholder commented on build_deploy.sh
ok i updated the build_deploy to just use the recipes. I also rebased the PR.

2023-07-19 10:13 UTC, Victoremepunto approved these changes

2023-07-19 10:31 UTC, Victoremepunto commented
@mjholder  please rebase and lets get this merged, thanks ! :+1:

2023-07-19 11:08 UTC, merged